# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Image = QtWidgets.QLabel(self.centralwidget)
        self.Image.setObjectName("Image")
        self.verticalLayout_2.addWidget(self.Image)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.change = QtWidgets.QPushButton(self.centralwidget)
        self.change.setObjectName("change")
        self.horizontalLayout_3.addWidget(self.change)
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setObjectName("add")
        self.horizontalLayout_3.addWidget(self.add)
        self.delete = QtWidgets.QPushButton(self.centralwidget)
        self.delete.setObjectName("delete")
        self.horizontalLayout_3.addWidget(self.delete)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.setStretch(0, 3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.LayText = QtWidgets.QVBoxLayout()
        self.LayText.setObjectName("LayText")
        self.Text = QtWidgets.QTextEdit(self.centralwidget)
        self.Text.setObjectName("Text")
        self.LayText.addWidget(self.Text)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.reduction = QtWidgets.QPushButton(self.centralwidget)
        self.reduction.setObjectName("reduction")
        self.horizontalLayout_2.addWidget(self.reduction)
        self.output = QtWidgets.QPushButton(self.centralwidget)
        self.output.setObjectName("output")
        self.horizontalLayout_2.addWidget(self.output)
        self.copy = QtWidgets.QPushButton(self.centralwidget)
        self.copy.setObjectName("copy")
        self.horizontalLayout_2.addWidget(self.copy)
        self.LayText.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.LayText)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图片转文字"))
        self.Image.setText(_translate("MainWindow", ""))
        self.change.setText(_translate("MainWindow", "转换"))
        self.add.setText(_translate("MainWindow", "添加"))
        self.delete.setText(_translate("MainWindow", "删除"))
        self.reduction.setText(_translate("MainWindow", "还原"))
        self.output.setText(_translate("MainWindow", "输出"))
        self.copy.setText(_translate("MainWindow", "复制"))



